name: Daily Commit

on:
  schedule:
    - cron: "0 12 * * *"  

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Clon the repo 
        uses: actions/checkout@v3

      - name: Update the file 
        run: echo "$(date)" > last_commit.txt
          
      - name: Değişiklikleri Git'e Kaydet
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "sracboran@gmail.com"
          git add .
          git commit -m "Automated commit - $(date)"
          git push
